home: "{{ ansible_env.HOME }}"

base_apps:
  - git
  - vim
  - stow
  - openssh-server
  - python3
  - python3-pip
  - python3-venv

  - firefox
  - telegram-desktop
  - zathura

  - x11-utils
  - xdo
  - xdotool
  - xclip
  - libnotify-bin
  - bluez
  - blueman
  - network-manager
  - pulseaudio
  - pavucontrol

dev_install: true
dev_apps:
  - build-essential
  - shellcheck
pipx_apps:
  - jedi-language-server
  - yamllint
  - "ansible-lint[community,yamllint]"
stylua_url: "https://github.com/JohnnyMorganz/StyLua/releases/\
             download/v0.11.3/stylua-0.11.3-linux.zip"

optional_install: false
optional_apps:
  - vlc
  - vagrant

ricing: true
ricing_apps:
  - bspwm
  - sxhkd
  - dunst
  - rofi
  - feh
  - scrot

# dotfiles
dotfiles_repo_url: "https://github.com/kencx/dotfiles"
dotfiles_repo_path: "{{ home }}/dotfiles"
config_path: "{{ home }}/.config"

# fonts
font_repo_url: https://github.com/ryanoasis/nerd-fonts/releases/download
font_version: v2.1.0
font_name: FiraCode
font_dir: "{{ ansible_env.HOME }}/.local/share/fonts"

# startpage
firefox_path: "{{ home }}/.mozilla"
startpage_url: "https://github.com/kencx/startpage"
startpage_dest: "{{ firefox_path }}/startpage"

# binaries
binaries:
  - url: "https://github.com/junegunn/fzf/releases/download/0.29.0/fzf-0.29.0-linux_amd64.tar.gz"
    wildcard: ""

  - url: "https://github.com/ajeetdsouza/zoxide/releases/download/v0.8.0/zoxide-v0.8.0-x86_64-unknown-linux-musl.tar.gz"
    wildcard: "zoxide"

  - url: "https://github.com/rfjakob/gocryptfs/releases/download/v2.2.1/gocryptfs_v2.2.1_linux-static_amd64.tar.gz"
    wildcard: 'gocryptfs'

  - url: "https://github.com/xxxserxxx/gotop/releases/download/v4.1.2/gotop_v4.1.2_linux_amd64.tgz"
    wildcard: "gotop"

  - url: "https://github.com/dylanaraps/pfetch/archive/refs/tags/0.6.0.tar.gz"
    wildcard: "pfetch-0.6.0/pfetch"
    opts: "{{ strip }}"

  - url: "https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep-13.0.0-x86_64-unknown-linux-musl.tar.gz"
    wildcard: "ripgrep-13.0.0-x86_64-unknown-linux-musl/rg"
    opts: "{{ strip }}"

  - url: "https://github.com/sharkdp/bat/releases/download/v0.19.0/bat-v0.19.0-x86_64-unknown-linux-gnu.tar.gz"
    wildcard: "bat-v0.19.0-x86_64-unknown-linux-gnu/bat"
    opts: "{{ strip }}"

  - url: "https://github.com/sharkdp/fd/releases/download/v8.3.1/fd-v8.3.1-x86_64-unknown-linux-gnu.tar.gz"
    wildcard: "fd-v8.3.1-x86_64-unknown-linux-gnu/fd"
    opts: "{{ strip }}"
