---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 86400
    - name: Install git, vim
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - git
        - vim
    - name: Create user debian
      user:
        name: debian
        shell: /bin/bash
        create_home: true
        state: present
