---
- name: Verify
  hosts: all
  gather_facts: false
  vars:
    user: "debian"
    user_home: "/home/{{ user }}"
  tasks:
    - name: .vimrc exists
      stat:
        path: "{{ user_home }}/.vimrc"
      register: vimrc

    - debug:
        msg: "{{ user_home }}/.vimrc exists"
      when: vimrc.stat.exists

    - name: Check gitconfig
      become: true
      become_user: "{{ user }}"
      command: git config -l
      register: gitconfig
      failed_when: |
        "user.name=username" not in gitconfig.stdout

    - name: .bash_aliases exists
      stat:
        path: "{{ user_home }}/.bash_aliases"
      register: bash_aliases

    - debug:
        msg: ".bash_aliases exists"
      when: bash_aliases.stat.exists
