---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 86400
    - name: Run goss role
      include_role:
        name: goss
