---
- name: Install fail2ban
  package:
    name: fail2ban
    state: present

- name: Add sshd jail config
  template:
    src: sshd.local.j2
    dest: /etc/fail2ban/jail.d/sshd.local
    owner: root
    group: root
    mode: 0644
  notify: Restart fail2ban

- name: Start and enable fail2ban
  service:
    name: fail2ban
    enabled: true
    state: started
