---
- name: Install fail2ban
  become: true
  apt:
    name: fail2ban
    state: present

- name: Copy fail2ban custom config file
  become: true
  template:
    src: "{{ fail2ban_config_file }}"
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644
  # notify: restart fail2ban

- name: Ensure fail2ban is running and enabled
  become: true
  service:
    name: fail2ban
    state: started
    enabled: true
  when:
    start_fail2ban | bool
