---
- name: Add sudo rights
  become: true
  lineinfile:
    dest: /etc/sudoers
    regexp: "^{{ item }}"
    line: "{{ item }} ALL=(ALL) ALL"
    state: present
    validate: 'visudo -cf %s'
    mode: 0644
  with_items: "{{ sudoers }}"
