---
- name: Add sudo rights
  copy:
    content: |
      {% for group in sudoers %}
      %{{ group }} ALL=(ALL:ALL) ALL
      {% endfor %}
    dest: "/etc/sudoers.d/01-wheel"
    owner: root
    group: root
    mode: 0644
    validate: 'visudo -cf %s'
