---
- name: install dev apps
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ dev_apps | default([]) }}"

- name: install pipx apps
  become: false
  community.general.pipx:
    name: "{{ item }}"
    state: present
  with_items: "{{ pipx_apps | default([]) }}"

  # check stylua version
- name: install stylua
  unarchive:
    src: "{{ stylua_url }}"
    dest: "{{ ansible_env.HOME }}/.local/bin"
    remote_src: true
    keep_newer: true

- name: install go
