---
- name: install apps
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ base_apps | default([]) }}"

- name: install pipx
  pip:
    name: pipx

- name: install st terminal

- name: install tmux

- name: install neovim

- name: install obsidian
- name: install st terminal

- name: install tmux

- name: install neovim

- name: install obsidian

- name: install redshift

- name: install binaries
  include_role:
    name: roles/apps/binary
  vars:
    strip: "--strip-components=1"

    binary_url: "{{ item.url }}"
    wildcard: "{{ item.wildcard | default('') }}"  # omit does not work, not sure why
    opts: "{{ item.opts | default('') }}"
  with_items: "{{ binaries }}"
