---
- name: Converge
  hosts: all
  collections:
    - kencx.homelab

  tasks:
    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 86400
    - include_role:
        name: security
