---
- name: Verify
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Check SSH is running
      service:
        name: ssh
        state: started
        enabled: true

    - name: Check ufw started
      service:
        name: ufw
        state: started
        enabled: true

    - name: Check fail2ban is running and enabled
      service:
        name: fail2ban
        state: started
        enabled: true
