---
- name: Install nfs-common package
  become: true
  apt:
    name: nfs-common
    state: present

- name: Mount NFS share
  become: true
  mount:
    src: "{{ nfs_share_path }}"
    path: "{{ nfs_mnt_path }}"
    fstype: nfs
    opts: "{{ nfs_opts }}"
    state: mounted
