---
- name: Assert variables defined
  assert:
    that:
      - webhook_nginx_server_name is defined
      - webhook_nginx_server_name | length == 0
    fail_msg: "webhook_nginx_server_name is not defined or is an empty string."

- name: Check letsencrypt directory exists for webhook
  stat:
    path: "{{ webhook_certbot_dir }}/live/{{ webhook_nginx_server_name }}"
  register: __webhook_cert_dir

- name: Fail if letsencrypt directory does not exist
  fail:
    msg: "Letsencrypt certificates not found for {{ webhook_nginx_server_name }}"
  when:
    - __webhook_cert_dir.stat.isdir is defined
    - not __webhook_cert_dir.stat.isdir

- name: Copy webhook.conf
  template:
    src: "webhook.conf.j2"
    dest: "{{ webhook_nginx_dir }}/conf.d/webhook.conf"
    owner: root
    group: root
    mode: 0644

- name: Reload nginx
  systemd:
    name: nginx
    state: reloaded
