---
- name: Check Python version
  command: "python3 --version"
  ignore_errors: true
  changed_when: false
  failed_when: false
  register: installed_python_version

- name: Extract version number
  set_fact:
    installed_python_version: "{{ (installed_python_version.stdout | split(' '))[1] }}"

- name: "Install Python {{ latest_python_version }}"
  apt:
    name: "{{ python_package }}"
    state: present
  when: installed_python_version is version(latest_python_version, '<')

- name: Install python3.9-venv
  apt:
    name: "{{ python_package }}-venv"
    state: present

- name: Install pip3
  apt:
    name: python3-pip
    state: present

  # install on root
- name: Install pipx
  pip:
    name: pipx
  when: install_pipx
  notify: ensurepath
