---
# startpage firefox
- name: check for firefox installation
  stat:
    path: "{{ firefox_path }}"
  register: firefox_exists

- name: clone startpage repo
  git:
    repo: "{{ startpage_url }}"
    dest: "{{ startpage_dest }}"
    clone: true
    update: true
  when: firefox_exists.stat.exists
