---
# fonts
- name: Ensure font directory exists
  file:
    path: "{{ font_dir }}"
    state: directory

- name: Download and extract fonts
  unarchive:
    src: "{{ font_repo_url }}/{{ font_version }}/{{ font_name }}.zip"
    dest: "{{ font_dir }}"
    remote_src: true
    exclude: "*Windows*"

- name: Run font cache check
  shell: fc-cache -fv
  register: fccache
  changed_when: false
  failed_when: "'fc-cache: succeeded' not in fccache.stdout"
