---
- name: clone dotfiles repo
  git:
    repo: "{{ dotfiles_repo_url }}"
    dest: "{{ dotfiles_repo_path }}"
    clone: true
    update: true

- name: stow all dotfiles
  make:
    chdir: "{{ dotfiles_repo_path }}"
    target: "dev"

# - name: Ensure config directory exists
#   file:
#     path: "{{ config_path }}/nvim"
#     state: directory

- name: Install fonts
  import_tasks: fonts.yml

- name: Add desktop files
  import_tasks: desktop.yml

- name: Add firefox startpage
  import_tasks: firefox.yml
