---
# ssh
ssh_port: 22
ssh_disable_root_login: true
ssh_disable_password_auth: true
ssh_disable_gateway_ports: true
ssh_login_grace_time: 30
ssh_max_auth_tries: 3
ssh_max_sessions: 3
ssh_max_startups: 3

# groups with sudo privileges - sudo, wheel etc.
sudoers: [sudo]

# fail2ban
fail2ban_config_file: "jail.local.j2"

# handlers
skip_handlers: false
