---
- name: Restart ssh
  service:
    name: ssh
    state: restarted
  when:
    - skip_handlers | default("false") == "false"

- name: Restart fail2ban
  service:
    name: fail2ban
    state: restarted
  when:
    - skip_handlers | default("false") == "false"

- name: Restart ufw
  community.general.ufw:
    state: reloaded
  when:
    - skip_handlers | default("false") == "false"
