name: CI
on: push
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Pre-commit
        uses: pre-commit/action@v2.0.3
        with:
          extra_args: --all-files

  # molecule:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #
  #     - name: Setup Python
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: '3.10'
  #
  #     - name: Install test dependencies
  #       run: pip3 install ansible-core molecule[docker] docker
  #
  #     # security has no support for molecule-docker
  #     - name: Molecule
  #       run: molecule test -s security
  #       env:
  #         ANSIBLE_FORCE_COLOR: "1"
