name: CI
on: push
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Pre-commit
        uses: pre-commit/action@v2.0.3
        with:
          extra_args: --all-files

  molecule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install test dependencies
        run: pip3 install ansible molecule[docker] docker

      - name: Test dotfiles
        run: molecule test -s dotfiles
        env:
          ANSIBLE_FORCE_COLOR: "1"

      - name: Test terraform
        run: molecule test -s terraform
        env:
          ANSIBLE_FORCE_COLOR: "1"

      - name: Test python3
        run: molecule test -s python3
        env:
          ANSIBLE_FORCE_COLOR: "1"

      # - name: Count number of molecule scenarios
      #   run: echo "NUM_OF_SCENARIOS=$(ls -d molecule/* | wc -l)" >> $GITHUB_ENV

      # - name: Run all tests in parallel
      #   run: "make molecule/* -j${{ env.NUM_OF_SCENARIOS }} -O"
      #   env:
      #     ANSIBLE_FORCE_COLOR: "1"
